import React from 'react';
import { Container, Typography, Box, Link } from '@mui/material';

const PrivacyPolicy: React.FC = () => {
  return (
    <Container maxWidth="sm" sx={{ py: 6, px: 3 }}>
      <Typography variant="h4" fontWeight={700} gutterBottom>
        Privacy Policy
      </Typography>
      <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 4 }}>
        Effective date: 27 March 2026
      </Typography>

      <Typography paragraph>
        Money Flow ("the App") is a personal finance tracker that helps you manage your spending and budgets. Your privacy matters to us. This policy explains what data we collect, how we use it, and your rights.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Data We Collect</Typography>
      <Box component="ul" sx={{ pl: 2, color: 'text.secondary' }}>
        <li><Typography><strong>Account data:</strong> Your email address and a securely hashed password, stored on our backend server.</Typography></li>
        <li><Typography><strong>Transaction data:</strong> Income and expense records you create — amounts, categories, notes, and dates. Associated with your account only, never shared.</Typography></li>
        <li><Typography><strong>Device preferences:</strong> Notification settings, display currency, and theme preference stored locally on your device using encrypted storage.</Typography></li>
        <li><Typography><strong>Receipt images:</strong> If you use AI receipt scanning, the image is sent to Anthropic's API for text extraction and then discarded. We do not store receipt images.</Typography></li>
      </Box>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Data We Do NOT Collect</Typography>
      <Box component="ul" sx={{ pl: 2, color: 'text.secondary' }}>
        <li><Typography>We do not collect location data.</Typography></li>
        <li><Typography>We do not collect advertising identifiers or device fingerprints.</Typography></li>
        <li><Typography>We do not use third-party analytics (e.g. Firebase, Mixpanel).</Typography></li>
        <li><Typography>We do not sell or share your data with third parties for any purpose.</Typography></li>
      </Box>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>How We Use Your Data</Typography>
      <Typography paragraph color="text.secondary">
        Your data is used solely to provide the App's features — displaying your transactions, computing budget summaries, and generating your weekly spending narrative. The narrative is generated by sending anonymised aggregate statistics (totals and category names, no personal identifiers) to Anthropic's API.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Data Storage and Security</Typography>
      <Typography paragraph color="text.secondary">
        Account and transaction data is stored on Railway-hosted infrastructure with MongoDB. Passwords are hashed with bcrypt and never stored in plain text. All API communication uses HTTPS/TLS. Auth tokens are stored in your device's secure enclave.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Backups</Typography>
      <Typography paragraph color="text.secondary">
        If you use the iCloud or Google Drive backup feature, your encrypted transaction data is written to your personal cloud storage. We do not have access to your cloud storage.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Data Retention and Deletion</Typography>
      <Typography paragraph color="text.secondary">
        Your data is retained as long as your account is active. You may delete your account at any time from Settings → Account → Delete Account. This permanently removes all your data from our servers.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Children's Privacy</Typography>
      <Typography paragraph color="text.secondary">
        The App is not directed at children under the age of 13. We do not knowingly collect personal data from children.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Changes to This Policy</Typography>
      <Typography paragraph color="text.secondary">
        We may update this policy occasionally. When we do, we will update the effective date above. Continued use of the App after changes constitutes acceptance of the updated policy.
      </Typography>

      <Typography variant="h6" fontWeight={700} sx={{ mt: 3, mb: 1 }}>Contact</Typography>
      <Typography color="text.secondary">
        If you have questions about this privacy policy or want to request data deletion, please open an issue at{' '}
        <Link href="https://github.com/wkliwk/money-flow-mobile/issues" target="_blank" rel="noopener">
          github.com/wkliwk/money-flow-mobile/issues
        </Link>.
      </Typography>
    </Container>
  );
};

export default PrivacyPolicy;
